### ISSUE TITLE
import error when executing JuliaBox database preperation on google cloud instance.

### ISSUE THREAD

**Issue by fqiang** [JuliaCloud/JuliaBox#469]
This error happens when trying deploy on google clouding computing instance. 
```python
Traceback (most recent call last):
  File "JuliaBox/scripts/install/create_tables_sqlite.py", line 9, in <module>
    from juliabox.db import JBoxUserV2, JBoxDynConfig, JBoxSessionProps, JBoxInstanceProps, JBPluginDB,\
  File "JuliaBox/scripts/install/../../engine/src/juliabox/db/__init__.py", line 2, in <module>
    from user_v2 import JBoxUserV2
  File "JuliaBox/scripts/install/../../engine/src/juliabox/db/user_v2.py", line 5, in <module>
    from boto.dynamodb2.fields import HashKey, RangeKey, GlobalKeysOnlyIndex
ImportError: cannot import name GlobalKeysOnlyIndex
```
I am not very familiar with python and also new to google cloud. I didn't encounter this error when deploy on an aws instance, neither on my local machine.

**Comment by nkottary** [comment]
You need to update the boto package.

**Comment by fqiang** [comment]
Thanks @nkottary.  After running ```pip install -U boto```, the db script executes successfully.
