### ISSUE TITLE
"No plugin found for vol.config" in enginedaemon.log preventing sessions

### ISSUE THREAD

**Issue by ianshmean** [JuliaCloud/JuliaBox#473]
From a fresh install, the 'creating instance' page is hanging with the following error in `enginedaemon.log`

```
2016-10-06 12:44:32,420 - ERROR - juliabox.srvr_jboxd.JBoxd - Exception in jbo$
Traceback (most recent call last):
  File "/jboxengine/src/juliabox/srvr_jboxd.py", line 25, in wrapper
    f(*args, **kwargs)
  File "/jboxengine/src/juliabox/srvr_jboxd.py", line 169, in launch_session
    JBoxd._launch_session(name, email, reuse)
  File "/jboxengine/src/juliabox/jbox_util.py", line 46, in f_retry
    rv = f(*args, **kwargs)  # first attempt
  File "/jboxengine/src/juliabox/srvr_jboxd.py", line 146, in _launch_session
    cont = SessContainer.launch_by_name(name, email, reuse=reuse)
  File "/jboxengine/src/juliabox/interactive/sess_container.py", line 122, in $
    cont = SessContainer._create_new(name, email)
  File "/jboxengine/src/juliabox/interactive/sess_container.py", line 66, in _$
    cfg_disk = VolMgr.get_cfg_mount_for_user(email)
  File "/jboxengine/src/juliabox/vol/volmgr.py", line 141, in get_cfg_mount_fo$
    raise Exception("No plugin found for %s" % (JBoxVol.JBP_CONFIG,))
Exception: No plugin found for vol.config
```

**Comment by barche** [comment]
Did you add the `juliabox.plugins.vol_defcfg` plugin in `jbox.user`?

**Comment by ianshmean** [comment]
Bingo. I was copying an older jbox.user file across and missed that new addition. Much appreciated
