### ISSUE TITLE
Error when deleting a directory

### ISSUE THREAD

**Issue by sivapvarma** [JuliaCloud/JuliaBox#477]
I get a pop up with the following message when I try to delete a user created directory "Tutorial" which is a copy of the stock "tutorial" directory. 

> Delete Failed.
> An error occurred when deleting "Tutorial"
> > Traceback (most recent call last): File "/usr/local/lib/python2.7/dist-packages/IPython/html/base/handlers.py", line 441, in wrapper result = yield gen.maybe_future(method(self, *args, **kwargs)) File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1008, in run value = future.result() File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 232, in result raise_exc_info(self._exc_info) File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 282, in wrapper yielded = next(result) File "/usr/local/lib/python2.7/dist-packages/IPython/html/services/contents/handlers.py", line 252, in delete yield gen.maybe_future(cm.delete(path)) File "/usr/local/lib/python2.7/dist-packages/IPython/html/services/contents/manager.py", line 228, in delete self.delete_file(path) File "/usr/local/lib/python2.7/dist-packages/IPython/html/services/contents/filemanager.py", line 437, in delete_file shutil.rmtree(os_path) File "/usr/lib/python2.7/shutil.py", line 232, in rmtree onerror(os.path.islink, path, sys.exc_info()) File "/usr/lib/python2.7/shutil.py", line 230, in rmtree raise OSError("Cannot call rmtree on a symbolic link") OSError: Cannot call rmtree on a symbolic link

**Comment by tanmaykm** [comment]
The stock `tutorial` directory is a link, not a regular directory. Looks like the Jupyter filemanager is calling `rmtree` on it which is failing. Can you check if it fails similarly on any linked directory?
