### ISSUE TITLE
'attempt to write a readonly database' preventing session after gauth

### ISSUE THREAD

**Issue by ianshmean** [JuliaCloud/JuliaBox#478]
This issue is preventing google login after a fresh install

I assume it's an issue with `/jboxengine/data/db/juliabox.db` being writeable, but I've not been able to fix it through chown. It's currently:
```
$ ls -l /jboxengine/data/db/juliabox.db
-rw-r--r-- 1 root root 20480 Oct 22 19:25 /jboxengine/data/db/juliabox.db
```
This is the only error being raised in the logs and I've not seen this before.

```
HTTPServerRequest(protocol='http', host='juliabox.splashband.io', method='GET', uri='/jboxauth/google/?state=xxx$
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1425, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 314, in wrapped
    ret = fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1638, in future_complete
    f.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "/jboxengine/src/juliabox/plugins/auth_google/google_auth.py", line 152, in get
    self.post_auth_launch_container(user_id)
  File "/jboxengine/src/juliabox/handlers/handler_base.py", line 426, in post_auth_launch_container
    jbuser = JBoxUserV2(user_id, create=True)
  File "/jboxengine/src/juliabox/db/user_v2.py", line 119, in __init__
    self.create(data)
  File "/jboxengine/src/juliabox/db/db_base.py", line 31, in create
    JBoxDB.DB_IMPL.record_create(cls.table(), data)
  File "/jboxengine/src/juliabox/plugins/db_sqlite3/impl_sqlite3.py", line 205, in record_create
    table.insert(data)
  File "/jboxengine/src/juliabox/plugins/db_sqlite3/impl_sqlite3.py", line 51, in insert
    c.execute(self.insert_statement, tuple(values))
OperationalError: attempt to write a readonly database
2016-10-22 19:25:53,919 - ERROR - tornado.access - 500 GET /jboxauth/google/?state=xxxx$

```

**Comment by ianshmean** [comment]
This is using a newly generated local juliaboxpkgdist docker image

**Comment by ianshmean** [comment]
Solved.. I had erroneously run the following as sudo

`JuliaBox/scripts/install/create_tables_sqlite.py /jboxengine/data/db/juliabox.db`
